Feature/limit access
tc-g8/acme-explorer pull request #19
Opened 2023-04-06 11:31 UTC by alemunara

2023-04-09 18:52 UTC, mrf1989 requested changes
Además de los aspectos comentados en el routing, la imagen que se usar para mostrar el acceso denegado no es responsive.

En Boostrap se dispone de la forma de hacerla adaptable a diferentes tamaños de layout.

2023-04-09 18:52 UTC, mrf1989 commented on src/app/app-routing.module.ts
> +      { path: ':id', component: DisplayTripComponent, canActivate: [ActorRoleGuard], data: {expectedRole: 'explorer|manager'} },
En este caso se está descartando la posibilidad de que un usuario anónimo pueda ver la vista detalle de un trip. No es correcto, ya que esto es un requisito que se incluye en el pliego. Se tendría que incluir.

2023-04-09 18:52 UTC, mrf1989 commented on src/app/app-routing.module.ts
> +  { path: 'me', component: ProfileComponent, canActivate: [ActorRoleGuard], data: {expectedRole: 'manager|sponsor|administrator'} },
Aquí no se contempla que un explorer pueda acceder a su perfil. Es un requisito obligado el permitir que todo usuario registrado en el sistema tenga acceso a su perfil.

2023-04-10 14:54 UTC, alemunara commented on src/app/app-routing.module.ts
> +  { path: 'me', component: ProfileComponent, canActivate: [ActorRoleGuard], data: {expectedRole: 'manager|sponsor|administrator'} },
cambios corregidos

2023-04-10 16:09 UTC, merged