feat: do not show counter if trip already started
tc-g8/acme-explorer pull request #47
Opened 2023-04-28 12:01 UTC by alemunara

2023-04-28 18:00 UTC, marmolpen3 commented
En el listado de los viajes sigue apareciendo que quedan pocos días para que inicie un viaje cuando ya ha empezado.

2023-04-29 08:45 UTC, mrf1989 approved these changes

2023-04-29 08:47 UTC, mrf1989 commented
Es cierto lo que dice Elena. Si como decía Alex está bien que siga apareciendo el trip...mejor que aparezca también resaltado de otra forma, o como desactivado o algo, para que el usuario pueda entender que ya no tiene opciones con ese.

2023-04-29 08:47 UTC, mrf1989 requested changes
Diferenciar el viaje en el listado si ha empezado

2023-04-29 10:07 UTC, marmolpen3 approved these changes

2023-04-29 10:07 UTC, merged